### PR TITLE
An es index can not start with a dash (-)

### PR DESCRIPTION
**Pull request by icybin**
In case there is a dash, replace them with "idx-"

### CODE REVIEW

**Comment by blueimp** [comment]
Thanks for your contribution, @kyanh-huynh 
If you replace the line with the following, I'll gladly merge it:

```js
  const index = payload.logGroup
    .replace(/\W+|_+/g, '-')
    .replace(/^\-/, '')
    .toLowerCase()
```

This uses a single dash for continuous replacements and simply removes a leading dash.

**Comment by icybin** [comment]
Thanks @blueimp . I've updated my PR. Is that better now?

**Comment by blueimp** [comment]
Almost there! :D
If you remove the semicolon (I follow the JS Standard style) and the superfluous newline, it's perfect. :)

**Comment by icybin** [comment]
I've fixed. I come from Ruby so nodejs is so fun :) Thanks again I will note for next time ;)

**Comment by blueimp** [comment]
Thanks again @kyanh-huynh !

**Pull request merged**
